Repository Greenfoot5/BattleBot, pull requests merged in 2020-03, with the labels that each got.

#16 Subscriptions
  BattleBot.py
  cogs/subscriptions.py
  data/subscriptions.json
  data/subscriptions.json.example
Labels: feature

#19 Profile search extended
  cogs/profiles.py
Labels: awaiting pull, enhancement, feature

#20 Fix import + remove extension
  BattleBot.py
  cogs/clans.py
Labels: awaiting pull, bug

#21 Fix handling of found discord user without database entry
  cogs/profiles.py
Labels: bug
