Repository Greenfoot5/BattleBot, pull requests merged in 2020-06, with the labels that each got.

#38 Data handler fail safe
  data/data_handler.py
Labels: awaiting pull, bug

#39 Added the auto-responses.
  BattleBot.py
  cogs/responses.py
Labels: awaiting pull, feature

#42 Added subscription mentions, edits and deletes.
  cogs/subscriptions.py
Labels: enhancement
